import jsPDF from 'jspdf';
import html2pdf from 'html2pdf.js';

export const generatePDFReport = (candidateName, markdownText) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxLineWidth = pageWidth - margin * 2;
  
  let y = margin;

  const checkPageBreak = (addedHeight) => {
    if (y + addedHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
      return true;
    }
    return false;
  };

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(167, 139, 250); // #a78bfa
  doc.text('Resume Mentor AI', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text('Resume Analysis Report', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Meta info
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Candidate Name: ${candidateName}`, margin, y);
  y += 6;
  doc.text(`Analysis Date & Time: ${new Date().toLocaleString()}`, margin, y);
  y += 15;

  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y - 5, pageWidth - margin, y - 5);

  // Content
  const lines = markdownText.split('\n');

  lines.forEach(line => {
    let text = line.trim();
    if (!text) {
      if (y > margin) {
        y += 4;
        checkPageBreak(0);
      }
      return;
    }

    let isHeading = false;
    let isBullet = false;
    let headingTextToPrint = null;

    // Detect markdown headings
    if (text.startsWith('#')) {
      text = text.replace(/^#+\s/, '');
      isHeading = true;
    } else if (text.startsWith('- **') || text.startsWith('* **')) {
      // It's a bolded bullet point section like "- **Professional Summary**: details"
      const match = text.match(/^[-*]\s\*\*(.*?)\*\*(.*)/);
      if (match) {
        headingTextToPrint = match[1] + (match[2].startsWith(':') ? ':' : '');
        text = match[2].replace(/^:\s*/, '').trim();
      }
    } else if (text.startsWith('- ') || text.startsWith('* ')) {
      isBullet = true;
      text = text.substring(2).trim();
    }
    
    // Clean up remaining markdown bold/italic tags
    text = text.replace(/\*\*/g, '').replace(/\*/g, '').replace(/__/g, '').replace(/_/g, '');

    // Print bold bullet heading if found
    if (headingTextToPrint) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      checkPageBreak(8);
      doc.text(headingTextToPrint, margin, y);
      y += 6;
    }

    if (!text && headingTextToPrint) {
       return; // Only a heading on this line
    }

    if (isHeading) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      y += 4; // Extra space before heading
      checkPageBreak(8);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
    }

    const xPos = isBullet ? margin + 5 : margin;
    const textWidth = maxLineWidth - (isBullet ? 5 : 0);
    
    if (isBullet) {
      checkPageBreak(6);
      doc.text('•', margin, y);
    }

    const splitText = doc.splitTextToSize(text, textWidth);
    
    splitText.forEach(tLine => {
      checkPageBreak(6);
      doc.text(tLine, xPos, y);
      y += 6;
    });
    
    if (isHeading) {
      y += 2; // Extra space after heading
    }
  });

  // Add Footer to all pages
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text('Generated by Resume Mentor AI', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  doc.save(`${candidateName.replace(/[^a-zA-Z0-9]/g, '_')}_Resume_Report.pdf`);
};



export const generateImprovedResumePDF = async (candidateName, elementId) => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error('Resume preview element not found.');
  }

  const opt = {
    margin:       15,
    filename:     `${candidateName.replace(/[^a-zA-Z0-9]/g, '_')}_Improved_Resume.pdf`,
    image:        { type: 'jpeg', quality: 0.98 },
    html2canvas:  { scale: 2, useCORS: true, logging: false },
    jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  return html2pdf().set(opt).from(element).save();
};
